import React from 'react'
import { FaRegBell } from 'react-icons/fa'

export default function NotificationNew() {
  return (
    <div className="flex items-center justify-between mx-2 sm:mx-16">
      <div>
        <div className="dropdown relative">
          <a
            className="
          dropdown-toggle
          text-black
          font-medium
          text-xs
          
          uppercase
          rounded
          
          transition
          duration-150
          ease-in-out
          flex
        
        "
            href="#"
            type="button"
            id="dropdownMenuButton2"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            
            <div className="absolute inline-block top-0 right-0 bottom-auto left-auto translate-x-2/4 -translate-y-1/2 rotate-0 skew-x-0 skew-y-0 scale-x-100 scale-y-100 p-1.5 text-xs bg-green-900  rounded-full z-10"></div>
<div className="px-2 py-2 bg-primary hover:bg-primary flex items-center justify-center text-center rounded-lg shadow-lg">
<svg
                aria-hidden="true"
                focusable="false"
                data-prefix="fas"
                data-icon="bell"
                className="mx-auto text-white w-5"
                role="img"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 448 512"
              >
                <path
                  fill="currentColor"
                  // d="M224 512c35.32 0 63.97-28.65 63.97-64H160.03c0 35.35 28.65 64 63.97 64zm215.39-149.71c-19.32-20.76-55.47-51.99-55.47-154.29 0-77.7-54.48-139.9-127.94-155.16V32c0-17.67-14.32-32-31.98-32s-31.98 14.33-31.98 32v20.84C118.56 68.1 64.08 130.3 64.08 208c0 102.3-36.15 133.53-55.47 154.29-6 6.45-8.66 14.16-8.61 21.71.11 16.4 12.98 32 32.1 32h383.8c19.12 0 32-15.6 32.1-32 .05-7.55-2.61-15.27-8.61-21.71z"
                ></path>
                <FaRegBell size="30rem"/>
              </svg>
            </div>
          </a>
          <ul
            className="
          dropdown-menu
          min-w-max
          absolute
          hidden
          bg-primary
          text-base
          z-50
          float-left
          py-2
          list-none
          text-left
          rounded-lg
          shadow-lg
          mt-1
          m-0
          bg-clip-padding
          border-none
        "
            aria-labelledby="dropdownMenuButton2"
          >
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-texting
              hover:bg-bgprimary
            "
                href="#"
              >
                Notifications
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-texting
              hover:bg-bgprimary
            "
                href="#"
              >
                Notifications
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-texting
              hover:bg-bgprimary
            "
                href="#"
              >
                Notifications
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-texting
              hover:bg-bgprimary
            "
                href="#"
              >
                Notifications
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-texting
              hover:bg-bgprimary
            "
                href="#"
              >
                Notifications
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-texting
              hover:bg-bgprimary
            "
                href="#"
              >
                Notifications
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-texting
              hover:bg-bgprimary
            "
                href="#"
              >
                Notifications
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  )
}
