import React, { useState } from "react";

export default function UserDB({ name }) {
  const [open, setOpen] = useState(true);
  return (
    <div className="flex items-center justify-between">
      <div>
        <div className="dropdown relative">
          <a
            className="
          dropdown-toggle
          text-black
          font-medium
          text-xs
          leading-tight
          uppercase
          rounded
          
          transition
          duration-150
          ease-in-out
          flex
          items-center
        "
            href="#"
            type="button"
            id="dropdownMenuButton2"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <div className="flex justify-center items-center">
              <div>
                <img
                  src="https://mdbcdn.b-cdn.net/img/new/avatars/8.webp"
                  className="rounded-full w-10 hidden sm:flex"
                  alt="Avatar"
                />
              </div>

              <div className="flex flex-row text-primary font-bold justify-between w-[100%]">
                <div>{name}</div>
              </div>
            </div>

            <svg
              aria-hidden="true"
              focusable="false"
              data-prefix="fas"
              data-icon="caret-down"
              className="w-2 ml-2"
              role="img"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 320 512"
            >
              <path
                fill="#672626"
                d="M31.3 192h257.3c17.8 0 26.7 21.5 14.1 34.1L174.1 354.8c-7.8 7.8-20.5 7.8-28.3 0L17.2 226.1C4.6 213.5 13.5 192 31.3 192z"
              ></path>
            </svg>
          </a>
          <ul
            className="
          dropdown-menu
          min-w-max
          absolute
          hidden
          bg-primary
          text-base
          z-50
          float-left
          py-2
          list-none
          text-left
          rounded-lg
          shadow-lg
          mt-1
          m-0
          bg-clip-padding
          border-none
        "
            aria-labelledby="dropdownMenuButton2"
          >
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-texting
              hover:bg-bgprimary
            "
                href="#"
              >
                Rewards
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-texting
              hover:bg-bgprimary
            "
                href="#"
              >
                Gift Cards
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-texting
              hover:bg-bgprimary
            "
                href="#"
              >
                Security
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-texting
              hover:bg-bgprimary
            "
                href="#"
              >
                Privacy
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-texting
              hover:bg-bgprimary
            "
                href="#"
              >
                Customer Support
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-texting
              hover:bg-bgprimary
            "
                href="#"
              >
                Payment Methods
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-texting
              hover:bg-bgprimary
            "
                href="#"
              >
                Logout
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
}
